services:
  - type: web
    name: pizza-delivery-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ESEWA_PRODUCT_CODE
        sync: false
      - key: ESEWA_SECRET_KEY
        sync: false
      - key: ESEWA_PAYMENT_URL
        sync: false
      - key: ESEWA_STATUS_URL
        sync: false
